
FILE_NAME = "data/ICPC队伍信息表_20251018001555.xlsx"
CONTEST_NAME = "第50届ICPC国际大学生程序设计竞赛亚洲区域赛南京站"
CONTEST_SHORT_NAME = "2025ICPC南京站"
CONTEST_ID = 9227



SEND_AC_TO_CONTESTANTS    = False
SEND_AC_TO_COACH          = False
SEND_ERROR_TO_CONTESTANTS = False
SEND_ERROR_TO_COACH       = False

OPERATE_ICPC_GLOBAL       = True
